// <auto-generated />
using System;
using System.Collections.Generic;
using EduGuide_Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EduGuide_Backend.Migrations
{
    [DbContext(typeof(EgaidbContext))]
    [Migration("20260607142837_AddRoleAndSubscriptionTier")]
    partial class AddRoleAndSubscriptionTier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "AcademicYear", new[] { "FRESHMAN", "SOPHOMORE", "JUNIOR", "SENIOR", "GRADUATE", "POST_GRADUATE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ChatRole", new[] { "USER", "ASSISTANT", "SYSTEM" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "Gender", new[] { "MALE", "FEMALE", "OTHER", "PREFER_NOT_TO_SAY" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "NotificationType", new[] { "RECOMMENDATION", "QUIZ_RESULT", "ROADMAP_UPDATE", "COURSE_UPDATE", "JOB_ALERT", "SYSTEM", "CHAT" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "QuizCategory", new[] { "CAREER_INTEREST", "PERSONALITY", "SKILL_ASSESSMENT", "APTITUDE", "LEARNING_STYLE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "RecommendationStatus", new[] { "PENDING", "ACCEPTED", "REJECTED", "EXPIRED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "RecommendationType", new[] { "CAREER", "STREAM", "COURSE", "SKILL", "JOB" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ResumeStatus", new[] { "PENDING", "ANALYZED", "FAILED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "SubscriptionTier", new[] { "NEWBIE", "PRO", "PRO_PLUS" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "UserRole", new[] { "STUDENT", "ADMIN" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EduGuide_Backend.Models.AcademicRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("degree");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer")
                        .HasColumnName("endYear");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fieldOfStudy");

                    b.Property<double?>("Gpa")
                        .HasColumnType("double precision")
                        .HasColumnName("gpa");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("institution");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("isCurrent");

                    b.Property<double?>("Percentage")
                        .HasColumnType("double precision")
                        .HasColumnName("percentage");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profileId");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer")
                        .HasColumnName("startYear");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("academic_records_pkey");

                    b.HasIndex(new[] { "ProfileId" }, "academic_records_profileId_idx");

                    b.ToTable("academic_records", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.CareerGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("priority");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profileId");

                    b.Property<int?>("TargetYear")
                        .HasColumnType("integer")
                        .HasColumnName("targetYear");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("career_goals_pkey");

                    b.HasIndex(new[] { "ProfileId" }, "career_goals_profileId_idx");

                    b.ToTable("career_goals", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.CareerRoadmap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isCompleted");

                    b.Property<string>("Phases")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("phases");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<string>("TargetCareer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("targetCareer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("career_roadmaps_pkey");

                    b.HasIndex(new[] { "UserId" }, "career_roadmaps_userId_idx");

                    b.ToTable("career_roadmaps", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CredentialUrl")
                        .HasColumnType("text")
                        .HasColumnName("credentialUrl");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("expiryDate");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("issueDate");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profileId");

                    b.HasKey("Id")
                        .HasName("certifications_pkey");

                    b.HasIndex(new[] { "ProfileId" }, "certifications_profileId_idx");

                    b.ToTable("certifications", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.ChatHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sessionId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("chat_history_pkey");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "chat_history_userId_createdAt_idx");

                    b.HasIndex(new[] { "UserId", "SessionId" }, "chat_history_userId_sessionId_idx");

                    b.ToTable("chat_history", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("currency")
                        .HasDefaultValueSql("'INR'::text");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Duration")
                        .HasColumnType("text")
                        .HasColumnName("duration");

                    b.Property<int>("EnrolledCount")
                        .HasColumnType("integer")
                        .HasColumnName("enrolledCount");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.Property<string>("Level")
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("updatedAt");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("courses_pkey");

                    b.HasIndex(new[] { "Category" }, "courses_category_idx");

                    b.HasIndex(new[] { "IsActive" }, "courses_isActive_idx");

                    b.HasIndex(new[] { "Provider" }, "courses_provider_idx");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.Interest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profileId");

                    b.HasKey("Id")
                        .HasName("interests_pkey");

                    b.HasIndex(new[] { "ProfileId" }, "interests_profileId_idx");

                    b.HasIndex(new[] { "ProfileId", "Name" }, "interests_profileId_name_key")
                        .IsUnique();

                    b.ToTable("interests", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Experience")
                        .HasColumnType("text")
                        .HasColumnName("experience");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<DateTime>("PostedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("postedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SalaryRange")
                        .HasColumnType("text")
                        .HasColumnName("salaryRange");

                    b.PrimitiveCollection<List<string>>("Skills")
                        .HasColumnType("text[]")
                        .HasColumnName("skills");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("type")
                        .HasDefaultValueSql("'full-time'::text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("updatedAt");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("jobs_pkey");

                    b.HasIndex(new[] { "Category" }, "jobs_category_idx");

                    b.HasIndex(new[] { "Company" }, "jobs_company_idx");

                    b.HasIndex(new[] { "IsActive" }, "jobs_isActive_idx");

                    b.HasIndex(new[] { "PostedAt" }, "jobs_postedAt_idx");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.KnowledgeArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("industry");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("updatedAt");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("knowledge_articles_pkey");

                    b.HasIndex(new[] { "Category" }, "knowledge_articles_category_idx");

                    b.HasIndex(new[] { "Industry" }, "knowledge_articles_industry_idx");

                    b.ToTable("knowledge_articles", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("isRead");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("readAt");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("notifications_pkey");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "notifications_userId_createdAt_idx");

                    b.HasIndex(new[] { "UserId", "IsRead" }, "notifications_userId_isRead_idx");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("completedAt");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<double?>("MaxScore")
                        .HasColumnType("double precision")
                        .HasColumnName("maxScore");

                    b.Property<string>("Questions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("questions");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("startedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'in_progress'::text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<double?>("TotalScore")
                        .HasColumnType("double precision")
                        .HasColumnName("totalScore");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("quizzes_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("quizzes", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.QuizResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Analysis")
                        .HasColumnType("jsonb")
                        .HasColumnName("analysis");

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answers");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double>("MaxScore")
                        .HasColumnType("double precision")
                        .HasColumnName("maxScore");

                    b.Property<double>("Percentage")
                        .HasColumnType("double precision")
                        .HasColumnName("percentage");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid")
                        .HasColumnName("quizId");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("quiz_results_pkey");

                    b.HasIndex(new[] { "QuizId" }, "quiz_results_quizId_idx");

                    b.HasIndex(new[] { "UserId" }, "quiz_results_userId_idx");

                    b.ToTable("quiz_results", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("expiresAt");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reasoning");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("recommendations_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("recommendations", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("expiresAt");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("refresh_tokens_pkey");

                    b.HasIndex(new[] { "Token" }, "refresh_tokens_token_idx");

                    b.HasIndex(new[] { "Token" }, "refresh_tokens_token_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "refresh_tokens_userId_idx");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.ResumeAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Analysis")
                        .HasColumnType("jsonb")
                        .HasColumnName("analysis");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Feedback")
                        .HasColumnType("jsonb")
                        .HasColumnName("feedback");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fileName");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text")
                        .HasColumnName("fileUrl");

                    b.Property<string>("ParsedContent")
                        .HasColumnType("jsonb")
                        .HasColumnName("parsedContent");

                    b.Property<string>("Recommendations")
                        .HasColumnType("jsonb")
                        .HasColumnName("recommendations");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("resume_analysis_pkey");

                    b.HasIndex(new[] { "UserId" }, "resume_analysis_userId_idx");

                    b.ToTable("resume_analysis", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("skills_pkey");

                    b.HasIndex(new[] { "Category" }, "skills_category_idx");

                    b.HasIndex(new[] { "Name" }, "skills_name_key")
                        .IsUnique();

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.Strength", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Evidence")
                        .HasColumnType("text")
                        .HasColumnName("evidence");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profileId");

                    b.HasKey("Id")
                        .HasName("strengths_pkey");

                    b.HasIndex(new[] { "ProfileId" }, "strengths_profileId_idx");

                    b.HasIndex(new[] { "ProfileId", "Name" }, "strengths_profileId_name_key")
                        .IsUnique();

                    b.ToTable("strengths", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<int>("CompletionPct")
                        .HasColumnType("integer")
                        .HasColumnName("completionPct");

                    b.Property<string>("Country")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("country")
                        .HasDefaultValueSql("'India'::text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("dateOfBirth");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phoneNumber");

                    b.Property<bool>("ProfileComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("profileComplete");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("student_profiles_pkey");

                    b.HasIndex(new[] { "UserId" }, "student_profiles_userId_idx");

                    b.HasIndex(new[] { "UserId" }, "student_profiles_userId_key")
                        .IsUnique();

                    b.ToTable("student_profiles", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.StudentSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("isVerified");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("level");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profileId");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skillId");

                    b.Property<int?>("YearsExp")
                        .HasColumnType("integer")
                        .HasColumnName("yearsExp");

                    b.HasKey("Id")
                        .HasName("student_skills_pkey");

                    b.HasIndex(new[] { "ProfileId" }, "student_skills_profileId_idx");

                    b.HasIndex(new[] { "ProfileId", "SkillId" }, "student_skills_profileId_skillId_key")
                        .IsUnique();

                    b.HasIndex(new[] { "SkillId" }, "student_skills_skillId_idx");

                    b.ToTable("student_skills", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.SubjectMark", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademicRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("academicRecordId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Grade")
                        .HasColumnType("text")
                        .HasColumnName("grade");

                    b.Property<double>("Marks")
                        .HasColumnType("double precision")
                        .HasColumnName("marks");

                    b.Property<double>("MaxMarks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(100.0)
                        .HasColumnName("maxMarks");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subjectName");

                    b.HasKey("Id")
                        .HasName("subject_marks_pkey");

                    b.HasIndex(new[] { "AcademicRecordId" }, "subject_marks_academicRecordId_idx");

                    b.ToTable("subject_marks", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatarUrl");

                    b.Property<int>("ChatLimitRemaining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("chatLimitRemaining");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstName");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("isVerified");

                    b.Property<DateTime>("LastLimitReset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("lastLimitReset")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("lastLoginAt");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastName");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordHash");

                    b.Property<int>("Role")
                        .HasColumnType("UserRole")
                        .HasColumnName("role");

                    b.Property<int>("SubscriptionTier")
                        .HasColumnType("SubscriptionTier")
                        .HasColumnName("subscriptionTier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_idx");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.UserCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("completedAt");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("courseId");

                    b.Property<DateTime>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("enrolledAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'enrolled'::text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("user_courses_pkey");

                    b.HasIndex(new[] { "CourseId" }, "user_courses_courseId_idx");

                    b.HasIndex(new[] { "UserId", "CourseId" }, "user_courses_userId_courseId_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "user_courses_userId_idx");

                    b.ToTable("user_courses", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.UserJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("appliedAt");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("jobId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'saved'::text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("user_jobs_pkey");

                    b.HasIndex(new[] { "JobId" }, "user_jobs_jobId_idx");

                    b.HasIndex(new[] { "UserId" }, "user_jobs_userId_idx");

                    b.HasIndex(new[] { "UserId", "JobId" }, "user_jobs_userId_jobId_key")
                        .IsUnique();

                    b.ToTable("user_jobs", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.Weakness", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Evidence")
                        .HasColumnType("text")
                        .HasColumnName("evidence");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profileId");

                    b.HasKey("Id")
                        .HasName("weaknesses_pkey");

                    b.HasIndex(new[] { "ProfileId" }, "weaknesses_profileId_idx");

                    b.HasIndex(new[] { "ProfileId", "Name" }, "weaknesses_profileId_name_key")
                        .IsUnique();

                    b.ToTable("weaknesses", (string)null);
                });

            modelBuilder.Entity("EduGuide_Backend.Models.AcademicRecord", b =>
                {
                    b.HasOne("EduGuide_Backend.Models.StudentProfile", "Profile")
                        .WithMany("AcademicRecords")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("academic_records_profileId_fkey");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.CareerGoal", b =>
                {
                    b.HasOne("EduGuide_Backend.Models.StudentProfile", "Profile")
                        .WithMany("CareerGoals")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("career_goals_profileId_fkey");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.CareerRoadmap", b =>
                {
                    b.HasOne("EduGuide_Backend.Models.User", "User")
                        .WithMany("CareerRoadmaps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("career_roadmaps_userId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.Certification", b =>
                {
                    b.HasOne("EduGuide_Backend.Models.StudentProfile", "Profile")
                        .WithMany("Certifications")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("certifications_profileId_fkey");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.ChatHistory", b =>
                {
                    b.HasOne("EduGuide_Backend.Models.User", "User")
                        .WithMany("ChatHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chat_history_userId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.Interest", b =>
                {
                    b.HasOne("EduGuide_Backend.Models.StudentProfile", "Profile")
                        .WithMany("Interests")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("interests_profileId_fkey");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.Notification", b =>
                {
                    b.HasOne("EduGuide_Backend.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("notifications_userId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.Quiz", b =>
                {
                    b.HasOne("EduGuide_Backend.Models.User", "User")
                        .WithMany("Quizzes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("quizzes_userId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.QuizResult", b =>
                {
                    b.HasOne("EduGuide_Backend.Models.Quiz", "Quiz")
                        .WithMany("QuizResults")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("quiz_results_quizId_fkey");

                    b.HasOne("EduGuide_Backend.Models.User", "User")
                        .WithMany("QuizResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("quiz_results_userId_fkey");

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.Recommendation", b =>
                {
                    b.HasOne("EduGuide_Backend.Models.User", "User")
                        .WithMany("Recommendations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("recommendations_userId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.RefreshToken", b =>
                {
                    b.HasOne("EduGuide_Backend.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("refresh_tokens_userId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.ResumeAnalysis", b =>
                {
                    b.HasOne("EduGuide_Backend.Models.User", "User")
                        .WithMany("ResumeAnalyses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("resume_analysis_userId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.Strength", b =>
                {
                    b.HasOne("EduGuide_Backend.Models.StudentProfile", "Profile")
                        .WithMany("Strengths")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("strengths_profileId_fkey");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.StudentProfile", b =>
                {
                    b.HasOne("EduGuide_Backend.Models.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("EduGuide_Backend.Models.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("student_profiles_userId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.StudentSkill", b =>
                {
                    b.HasOne("EduGuide_Backend.Models.StudentProfile", "Profile")
                        .WithMany("StudentSkills")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("student_skills_profileId_fkey");

                    b.HasOne("EduGuide_Backend.Models.Skill", "Skill")
                        .WithMany("StudentSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("student_skills_skillId_fkey");

                    b.Navigation("Profile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.SubjectMark", b =>
                {
                    b.HasOne("EduGuide_Backend.Models.AcademicRecord", "AcademicRecord")
                        .WithMany("SubjectMarks")
                        .HasForeignKey("AcademicRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("subject_marks_academicRecordId_fkey");

                    b.Navigation("AcademicRecord");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.UserCourse", b =>
                {
                    b.HasOne("EduGuide_Backend.Models.Course", "Course")
                        .WithMany("UserCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_courses_courseId_fkey");

                    b.HasOne("EduGuide_Backend.Models.User", "User")
                        .WithMany("UserCourses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_courses_userId_fkey");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.UserJob", b =>
                {
                    b.HasOne("EduGuide_Backend.Models.Job", "Job")
                        .WithMany("UserJobs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_jobs_jobId_fkey");

                    b.HasOne("EduGuide_Backend.Models.User", "User")
                        .WithMany("UserJobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_jobs_userId_fkey");

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.Weakness", b =>
                {
                    b.HasOne("EduGuide_Backend.Models.StudentProfile", "Profile")
                        .WithMany("Weaknesses")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("weaknesses_profileId_fkey");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.AcademicRecord", b =>
                {
                    b.Navigation("SubjectMarks");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.Course", b =>
                {
                    b.Navigation("UserCourses");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.Job", b =>
                {
                    b.Navigation("UserJobs");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.Quiz", b =>
                {
                    b.Navigation("QuizResults");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.Skill", b =>
                {
                    b.Navigation("StudentSkills");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.StudentProfile", b =>
                {
                    b.Navigation("AcademicRecords");

                    b.Navigation("CareerGoals");

                    b.Navigation("Certifications");

                    b.Navigation("Interests");

                    b.Navigation("Strengths");

                    b.Navigation("StudentSkills");

                    b.Navigation("Weaknesses");
                });

            modelBuilder.Entity("EduGuide_Backend.Models.User", b =>
                {
                    b.Navigation("CareerRoadmaps");

                    b.Navigation("ChatHistories");

                    b.Navigation("Notifications");

                    b.Navigation("QuizResults");

                    b.Navigation("Quizzes");

                    b.Navigation("Recommendations");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ResumeAnalyses");

                    b.Navigation("StudentProfile");

                    b.Navigation("UserCourses");

                    b.Navigation("UserJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
